# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnPrteZgbdznYSZRaFqj7c52hOhv8AEs

Weather modelling using the quadratic Equation
"""

a = int(input("Enter value of a: "))
b = int(input("Enter value of b: "))
c = int(input("Enter value of c: "))
x = int(input("Enter value of x: "))

# Calculate y
y = (a * (x ** 2)) + (b * x) + c

# Output the value of y
print("Value of y:", y)
