# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnPrteZgbdznYSZRaFqj7c52hOhv8AEs

Weather modelling using the quadratic Equation
"""

a = int(input("Enter value of a: "))
b = int(input("Enter value of b: "))
c = int(input("Enter value of c: "))
x = int(input("Enter value of x: "))

# Calculate y
y = (a * (x ** 2)) + (b * x) + c

# Output the value of y
print("Value of y:", y)

# Read input from a file
with open('input.txt.txt', 'r') as file:
    a = int(file.readline().strip())
    b = int(file.readline().strip())
    c = int(file.readline().strip())
    x = int(file.readline().strip())

# Calculate y
y = (a * (x ** 2)) + (b * x) + c

print(f"Value of y: {y}")

with open('input.txt.txt', 'r') as file:
    a = int(file.readline().strip())
    b = int(file.readline().strip())
    c = int(file.readline().strip())

with open('input_x.txt', 'r') as file:
    x_values = [int(line.strip()) for line in file.readlines()]

for x in x_values:
    y = (a * (x ** 2)) + (b * x) + c
    print(f"Value of y for x={x}: {y}")